palooza/urls.py
from django.shortcuts     import redirect
from django.urls          import path
from django.views.generic import TemplateView
from .                    import views

app_name = 'palooza'
urlpatterns = [
    path('',             views.Standings.as_view(),   name='standings'),
    path('standings/',   views.Standings.as_view(),   name='standings'),
    path('about/',       views.About.as_view(),       name='about'),
    path('discounts/',   views.Discounts.as_view(),   name='discounts'),
    path('checkins/add', views.AddCheckins.as_view(), name='checkins_add')
]

triviatimelive/urls.py
from django.conf    import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls    import include, path
from django.conf    import settings
from django.conf.urls.static import static


app_name = 'triviatimelive'
urlpatterns = [
    path('', include('website.urls')),
    path('admin/', admin.site.urls),
    path('triviapalooza/', include('palooza.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls          import path
from django.views.generic import TemplateView
from .                    import views

app_name = 'website'
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('about/how-to-play/', views.HowToPlay.as_view(), name='how_to_play'),
    path('about/us/', views.About.as_view(), name='about'),
    path('contact/apply/', views.Apply.as_view(), name='apply'),
    path('contact/hire-us/', views.HireUs.as_view(), name='hire_us'),
    path('contact/questions/', views.ContactQuestions.as_view(), name='contact_questions'),
    path('events/<int:id>/<slug:slug>/', views.EventView.as_view(), name='event'),
    path('fbpost/<day>/', views.FBPost.as_view(), name='fbpost'),
    path('fbpost/<day>/raw/', views.FBPost.as_view(), {'raw': True}, name='fbpost_raw'),
    path('fbpost/<day>/url/', views.FBPost.as_view(), {'url': True}, name='fbpost_url'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('pennant/about/', views.PennantAbout.as_view(), name='pennant_about'),
    path('pennant/move/', views.MovePennant.as_view(), name='move_pennant'),
    path('pennant/standings/', views.PennantStandings.as_view(), name='pennant_standings'),
    path('pennant/standings/update/', views.UpdatePennantStandings.as_view(), name='update_standings'),
    path('venues/', views.Venues.as_view(), name='venues'),
]

website/forms.py
from django import forms

day_choices = (
    ('monday',    'Monday'),
    ('tuesday',   'Tuesday'),
    ('wednesday', 'Wednesday'),
    ('thursday',  'Thursday'),
    ('friday',    'Friday'),
    ('saturday',  'Saturday'),
    ('sunday',    'Sunday'))

class CapitalizedField(forms.CharField):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.widget=forms.TextInput(attrs={
            'autocorrect': 'off',
            'autocapitalize': 'words'})

class YesNoField(forms.ChoiceField):
    def __init__(self, *args, **kwargs):
        kwargs['widget']=forms.RadioSelect
        kwargs['choices']=( ('yes','Yes'), ('no','No') )
        super().__init__(*args, **kwargs)


# forms used in hire_us.html
class BusinessContactForm(forms.Form):
    business_name  = CapitalizedField()
    business_phone = forms.CharField()

    client_name  = CapitalizedField(label="Contact name")
    client_phone = forms.CharField(label="Phone")
    client_email = forms.EmailField(label="Email")

    business_type = forms.ChoiceField(
        choices=(
            ('restaurant/bar', 'Restaurant/Bar (serves food)'),
            ('taproom',        'Taproom (beer only)'),
            ('bar',       'Bar (drinks, but no food)'),
            ('other',          'Other')))
    business_type_other = forms.CharField(
            label="If other, please describe it.",
            required=False)

    survey_previous_trivia = forms.ChoiceField(
        label="Do you currently or have you ever run another trivia game before?",
        widget=forms.RadioSelect,
        choices=(
            ('yes','Yes'),
            ('no','No')))
    survey_previous_trivia_explain = forms.CharField(
        label="If so, whose game do/did you use?",
        required=False)

class EventContactForm(forms.Form):
    client_name  = CapitalizedField(label="Contact name")
    client_phone = forms.CharField(label="Phone")
    client_email = forms.EmailField(label="Email")

    event_summary = forms.CharField(label="What is your event?")
    event_date    = forms.DateField(label="Event Date (MM/DD/YY)",
        widget=forms.DateInput(attrs={'type': 'date'}),
        input_formats=['%m/%d/%Y', '%m/%d/%y'])
    event_location = forms.CharField()
    event_people  = forms.CharField(label="About how many people do you think will be there?")

class ContactTimeForm(forms.Form):
    contact_method = forms.ChoiceField(
        label="What's the best way to contact you?",
        choices=[
            ('email', 'Email'),
            ('phone', 'Phone')])
    contact_days = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
        label="Best days to reach you?",
        required=False,
        choices=day_choices)
    contact_time = forms.CharField(
        label="What's the best time to reach you?",
        required=False)

class SurveyHireUsForm(forms.Form):
    survey_questions = forms.CharField(widget=forms.Textarea,
        label="Do you have any questions for us before we contact you?",
        required=False)

class BusinessHireUsForm(SurveyHireUsForm, ContactTimeForm, BusinessContactForm):
    pass

class EventHireUsForm(SurveyHireUsForm, ContactTimeForm, EventContactForm):
    pass

# form used in apply.html
class ApplyForm(forms.Form):
    name = CapitalizedField()
    phone = forms.CharField()
    email = forms.EmailField()
    address = CapitalizedField()
    city = CapitalizedField()

    referral = CapitalizedField(
        label="How did you hear about us?")
    days_available = forms.MultipleChoiceField(
        label="What nights are you available to host?",
        widget=forms.CheckboxSelectMultiple,
        choices=day_choices)
    is_21 = YesNoField(label="Are you over 21?")
    has_transportation = YesNoField(
        label="Do you have reliable means of transportation?")
    has_laptop = YesNoField(
        label="Do you own a laptop?")
    has_media_player = YesNoField(
        label="Do you have iTunes or a similar means of playing music?")
    has_excel = YesNoField(
        label="Do you have Microsoft Excel or a similar means of using spreadsheets?")
    has_experience = YesNoField(
        label="Do you have any relevant experience? (not required, but a plus)")

    survey_reason = forms.CharField(widget=forms.Textarea,
        label="Why do you want to be a trivia host?")
    survey_played_before = YesNoField(
        label="Have you played our game before?")
    survey_played_before_explain = CapitalizedField(
        label="If so, where?",
        required=False)
    survey_extra_info = forms.CharField(widget=forms.Textarea,
        label="Is there anything else you'd like to tell us about yourself?",
        required=False)

# form used in login.html
class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

website/views.py
from datetime  import date, datetime, timezone, timedelta
from PIL import Image
from random    import choice
import re

from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout
from django.contrib.staticfiles import finders
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.shortcuts import render, redirect
from django.http      import HttpResponse, HttpResponseRedirect, Http404
from django.urls      import reverse
from django.urls.exceptions import NoReverseMatch
from django.utils     import dates
from django.utils.text import slugify
from django.views     import generic, View

from .models          import (Announcement, Clue, Event, Pennant,
                              PageContent, PennantDistrict, PennantStandings,
                              Venue)
from .forms           import BusinessHireUsForm, EventHireUsForm, LoginForm
from .util            import ordinal

LOGIN_URL = '/login/'

class Index(View):
    template_name = "website/index.html"

    def get(self, request):
        context = self.get_context()
        return render(request, self.template_name, context)

    def get_context(self):
        """ Return dict of today's games, clue, and announcements """
        today = date.today()
        # the Venue days are zero-indexed, but isoweekday is one-indexed,
        # hence the '-1'
        games = Venue.objects.filter(
            day=today.isoweekday()-1).order_by('time', 'name')
        games = list(filter(lambda v: not v.active_hold(), games))
        announcements = Announcement.objects.all().order_by('-display_start')
        active_announcements = list(filter(self.is_announcement_active, announcements))
        try:
            clue = Clue.objects.get(date=today)
        except Clue.DoesNotExist:
            clue = {'title': 'Coming Soon!', 'url': ''}
        return {
            'todays_games': games,
            'todays_clue': clue,
            'announcements': self.make_pennant_announcements() + active_announcements,
        }

    def is_announcement_active(self, ann):
        """ BOOL: True if now is between ann.display_start and ann.display_end datetimes """
        now = datetime.now(timezone.utc)
        if ann.display_end:
            return ann.display_start < now <= ann.display_end
        else:
            return ann.display_start < now

    def make_pennant_announcements(self):
        pennant_districts = PennantDistrict.objects.all()
        announcements = []
        for district in pennant_districts:
            pennant = Pennant.objects.get(district=district)
            venue = pennant.get_current_venue()

            if not venue:
                break

            game = pennant.update_next_game()
            preposition = 'in' if 'Bainbridge' not in venue.city() else 'on'
            if game == date.today():
                day = "Tonight"
            else:
                day = game.strftime('%A, %B ') + ordinal(game.day)
            if venue.city().lower() in venue.name.lower():
                description = '{day} at {venue} at {time}'.format(
                    day=day,
                    venue=venue.name,
                    time=venue.time.strftime('%l:%M%P'))
            else:
                description = '{day} at {venue} {prep} {city} at {time}'.format(
                    day=day,
                    venue=venue.name,
                    prep=preposition,
                    city=venue.city(),
                    time=venue.time.strftime('%l:%M%P'))
            announcement = {
                    'title': 'Next %s Game' % pennant,
                    'description': description}
            announcements.append(announcement)
        return announcements

class ContentPage(View):
    template_name = "website/content_page.html"
    context_object_name = "content"
    content_model = PageContent

    def __init__(self, *args, **kwargs):
        super(ContentPage, self).__init__(*args, **kwargs)
        if hasattr(self, 'extra_context') and self.extra_context:
            static_content = self.get_static_content()
            self.extra_context['static_content'] = static_content

    def get_static_content(self):
        """ get static content based on template name
            return string of html """
        if self.extra_context:
            template = self.extra_context.get('template', '')
            if template:
                name = template.split('/')[-1].split('.')[0]
                try:
                    static_content = self.content_model.objects.get(name=name)
                except self.content_model.DoesNotExist:
                    return None

                # parse out urls and reverse them
                # URLs are supplied with the following markup:
                #    url::website:about_us.html
                # urls that can't be reversed are prepended with "#bad_url:"
                url_regex = r'url::([\w\d_:]+)'
                def url_reverse(match):
                    expanded = match.expand(r'\1')
                    try:
                        return reverse(expanded)
                    except NoReverseMatch:
                        return "#bad_url:" + expanded
                content_with_urls_reversed = re.sub(
                    url_regex, url_reverse, static_content.content)

                # parse out static files and reverse (get) them
                # Static files are supplied with the following markup:
                #    file::website/images/logos/TTL-stand_up_for_kids_logo.svg
                static_regex = r'file::([\w\d\-_.:]+)'
                static_reverse = lambda match: static(match.expand(r'\1'))
                content_with_static_files_reversed = re.sub(
                    static_regex, static_reverse, content_with_urls_reversed)

                return content_with_static_files_reversed
        return None

class About(ContentPage, generic.TemplateView):
    extra_context = {
        "header": "About Us",
        "template": "website/about.html",
        "content": None,
        "meta_tags": [
            {"name": "description",
             "content": "The Pacific Northwest’s unrivaled live trivia \
             experience! Play for free and win prizes!"}]}

class HowToPlay(ContentPage, generic.TemplateView):
    extra_context = {
        "header": "How To Play / FAQ",
        "template": "website/how_to_play.html",
        "content": None}

class ContactQuestions(ContentPage, generic.TemplateView):
    extra_context = {
        "header": "Contact",
        "template": "website/contact_questions.html",
        "content": None}

class HireUs(ContentPage, generic.TemplateView):
    extra_context = {
        "header": "Hire Us",
        "template": "website/hire_us.html",
        "content": None,
        "business_form": BusinessHireUsForm,
        "event_form": EventHireUsForm,
        "meta_tags": [
            {"name": "robots",
             "content": "noindex, nofollow"}]}

class Apply(ContentPage, generic.TemplateView):
    extra_context = {
        "header": "Apply To Host",
        "template": "website/apply.html",
        "content": None,
        "meta_tags": [
            {"name": "robots",
             "content": "noindex, nofollow"}]}

class Venues(ContentPage, generic.ListView):
    extra_context = {
        "header": "Where To Play",
        "template": "website/venues.html",
        "today": date.today,
        "meta_tags": [
            {"name": "robots",
             "content": "noindex, nofollow"}]}

    def get_queryset(self):
        """ Return all venues ordered by their days and then names """
        def set_extra_venue_fields(venue):
            """ set next_date and logo_url properties """
            venue.next_date = venue.next_game(ignore_hold=True)
            return venue

        return [set_extra_venue_fields(v)
                for v in Venue.objects.order_by("day", "name")]

class PennantAbout(ContentPage, generic.TemplateView):
    extra_context = {
        "header": "What Is The Pennant?",
        "template": "website/pennant_about.html",
        "content": None}

class PennantStandings(ContentPage, generic.ListView):
    extra_context = {
        "header": "Pennant Standings",
        "template": "website/pennant_standings.html"}

    def get_queryset(self):
        """ Return all active venues """
        venues = Venue.objects.exclude(pennant_district=None)
        return list(sorted(venues,
            key=lambda v: (v.pennant_district.name,
                           -v.pennantstandings.total_points(),
                           v.name)))

class EventView(ContentPage, View):
    model = Event
    extra_context = {
        "template": "website/event.html",
    }
    def get(self, request, id, slug):
        try:
            event = self.model.objects.get(pk=id)
            header = "Events: " + event.title
        except Event.DoesNotExist:
            event = None
            header = "Event Not Found"

        bg_desktop_url, bg_mobile_url = (None, None)
        static_url = lambda x: x.replace('webapps/triviatimelive/ttl-website/static/', '')
        if event.bg_desktop:
            bg_desktop_url = static_url(event.bg_desktop.url)
        if event.bg_mobile:
            bg_mobile_url = static_url(event.bg_mobile.url)
        context = {
            "header": header,
            "bg_desktop_url": bg_desktop_url,
            "bg_mobile_url": bg_mobile_url,
            "content": event}

        bg_color_info = self.get_bg_color_info(event)

        context.update(bg_color_info)
        context.update(self.extra_context)
        return render(request, self.template_name, context)

    def color_distance(a, b):
        """ Return the distance (closeness) of two colors """
        return sqrt(abs((a[0] - b[0])^2 + (a[1] - b[1])^2 + (a[2] - b[2])^2))

    def most_common_color(self, im_url):

website/templates/website/about.html
<div class="main-centered">
    {{ static_content|safe }}
</div>

website/templates/website/contact_questions.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'website/contact_questions.css' %}" />

{{ static_content|safe }}

website/templates/website/hire_us.html
{% load static %}
<link rel="stylesheet" href="{% static 'website/form.css' %}">
<link rel="stylesheet" href="{% static 'website/hire_us.css' %}">
{% if success and not errors %}
<h2 class="success">
    Your request has been submitted! We will try to contact you as soon as
    possible.
</h2>
{% endif %}
{% if errors %}
<h2 class="error">Uh-oh, there was an error with your submission!</h2>
{% endif %}
<h2>Hire Us to host a game for you</h2>
<div class="main-centered">
    <p>
        Is this for a game at your business, or a private party/event?
    </p>

    <input type="radio" id="id_event_type0"
        name="event_type" value="business">
    <label for="id_event_type0">Business</label>

    <input type="radio" id="id_event_type1"
        name="event_type" value="event">
    <label for="id_event_type1">Private Event</label>

    <form method="post" id="business-form">
        {% csrf_token %}
        {{ business_form.as_p }}
        <input type="submit" value="Submit">
    </form>
    <form method="post" id="event-form">
        {% csrf_token %}
        {{ event_form.as_p }}
        <input type="submit" value="Submit">
    </form>
</div>

<script type="text/javascript" src="{% static 'website/util.js' %}"></script>
<script type="text/javascript">
    // client-side validation
    function validateBusiness(form) {
        // Validate and clean form data
        // trim all text inputs
        forEach(form.querySelectorAll('input[type=text]'),
            function(e) {e.value = e.value.trim();})
        var error,
            input,
            message,
            data = {
                csrfmiddlewaretoken: form.querySelector('[name=csrfmiddlewaretoken]').value,
                event_type: document.querySelector('[name=event_type]:checked').value,
                business_name: form.querySelector('[name=business_name]').value,
                business_phone: form.querySelector('[name=business_phone]')
                    .value.replace(/[- ]/g, ''),
                client_name: form.querySelector('[name=client_name]').value,
                client_phone: form.querySelector('[name=client_phone]')
                    .value.replace(/[- ]/, ''),
                client_email: form.querySelector('[name=client_email]').value,
                business_type: form.querySelector('[name=business_type]').value,
                business_type_other: form.querySelector(
                    '[name=business_type_other]').value,
                previous_trivia: form.querySelector(
                    'input[name=survey_previous_trivia]:checked').value,
                previous_trivia_explain: form.querySelector(
                    '[name=survey_previous_trivia_explain]').value,
                contact_method: form.querySelector('[name=contact_method]').value,
                contact_days: Array.prototype.map.call(
                    form.querySelectorAll('[name=contact_days]:checked'),
                    function(e) { return e.value }),
                contact_time: form.querySelector('[name=contact_time]').value,
                survey_questions: form.querySelector(
                    '[name=survey_questions]').value};

        if(data.business_phone.length < 10) {
            error = true;
            input = form.querySelector('[name=business_phone]');
            message = 'Please include an area code in your phone number';
        } else if(data.client_phone.length < 10) {
            error = true;
            input = form.querySelector('[name=client_phone]');
            message = 'Please include an area code in your phone number';
        } else if(data.business_type === 'other' && !data.business_type_other) {
            error = true;
            input = form.querySelector('[name=business_type_other]');
            message = 'Could you describe what type of venue it is?';
        } else if(data.previous_trivia === 'yes' && !data.previous_trivia_explain) {
            error = true;
            input = form.querySelector('[name=survey_previous_trivia_explain]');
            message = "You said that you've had a trivia game before. " +
                "Could you tell us whos? We're just curious.";
        }

        if (error) {
            errorMessage(input, message, {position: 'before'});
            input.focus();
            return false;
        } else {
            return data;
        }
    }

    function validateEvent(form) {
        // Validate and clean form data
        var error,
            input,
            message,
            data = {
                csrfmiddlewaretoken: form.querySelector('[name=csrfmiddlewaretoken]').value,
                event_type: document.querySelector('[name=event_type]:checked').value,
                client_name: form.querySelector('[name=client_name]').value,
                client_phone: form.querySelector('[name=client_phone]').value,
                client_email: form.querySelector('[name=client_email]').value,
                event_summary: form.querySelector('[name=event_summary]').value,
                event_date: form.querySelector('[name=event_date]').value,
                event_location: form.querySelector('[name=event_location]').value,
                event_people: form.querySelector('[name=event_people]').value,
                contact_method: form.querySelector('[name=contact_method]').value,
                contact_days: Array.prototype.map.call(
                    form.querySelectorAll('[name=contact_days]:checked'),
                    function(e) { return e.value }),
                contact_time: form.querySelector('[name=contact_time]').value,
                survey_questions: form.querySelector(
                    '[name=survey_questions]').value};

        // trim any extra spaces from the ends of values
        forEach(Object.keys(data), function(k) {
            var val = data[k];
            if(typeof(val) === "string")
                data[k] = data[k].trim();
        });

        if(data.client_phone.length < 10) {
            error = true;
            input = form.querySelector('[name=client_phone]'),
            message = 'Please include an area code in your phone number';
        } else if(!/^\d{4}-\d{2}-\d{2}/.test(data.event_date)) {
            var altDateFmt = /^(\d{2})\/(\d{2})\/(\d{2}|\d{4})$/;
            if(altDateFmt.test(data.event_date)) {
                data.eventDate.replace(altDateFmt, '\3-\2-\1');
            } else {
                error = true;
                input = form.querySelector('[name=event_date]'),
                message = 'Please enter a date in this format: MM/DD/YY';
            }
        }

        if (error) {
            errorMessage(input, message, {position: 'before'});
            input.focus();
            return false;
        } else {
            return data;
        }
    }

    function submitForm(e) {
        // determine which form was submitted, validate, clean, post data
        e.preventDefault();
        clearErrors();
        var form = e.target,
            data;
        switch(form.id) {
            // determine which form to validate
            case "business-form":
                data = validateBusiness(form);
                break;
            case "event-form":
                data = validateEvent(form);
                break;
            default:
                errorMessage(
                    form.querySelector('input[type=submit]'),
                    "Oops! Something went wrong!",
                    {position: 'before'});
                return false;
                break;
        }
        if(data) {
            // post the data
            post("{% url 'website:hire_us' %}", data);
        } else {
            // something's invalid; display error message
            errorMessage(
                form.querySelector('input[type=submit]'),
                "Oops! Something's invalid.",
                {position: 'before'});
        }
    }

    var businessForm = document.getElementById('business-form'),
        eventForm = document.getElementById('event-form');

    businessForm.onsubmit = submitForm;
    eventForm.onsubmit = submitForm;

    // if errors, repopulate the form with the data the user entered, with
    // error messages
    {% if errors %}
        {% for k,v in form_data.items %}
        // repopulate form with user's data
        var form = document.getElementById('{{form_data.event_type}}-form'),
            key = '{{k}}',
            val = '{{v}}',
            inp;
        if(key === 'event_type') {
            inp = document.querySelector('[name=' +key + '][value="{{v}}"]');
            if(inp) {
                inp.checked = "true";
            }
        } else {
            inp = form.querySelector('#id_' + key);
            if(inp) {
                if(inp.tagName === 'UL' && val) {
                    if(inp.id === 'id_contact_days') {
                        var days = val.toLowerCase().split(',');
                        days.forEach(function(d) {
                            var cb = inp.querySelector('[value=' + d + ']');
                            cb.checked = true;
                        });
                    } else {
                        var cb = inp.querySelector('[value={{v}}]');
                        cb.checked = true;
                    }
                } else {
                    inp.value = val;
                }
            }
        }
        {% endfor %}
        {% for error in errors %}
        {% for k,v in error.items %}
        // display any server-generated error messages
        var inp = form.querySelector('#id_{{k}}'),
            msg = "{{v}}";
        errorMessage(inp, msg, {position: 'before'});
        {% endfor %}
        {% endfor %}
    {% endif %}
</script>

website/templates/website/how_to_play.html
{% load static %}

{{ static_content|safe }}

website/templates/website/login.html
{% load static %}
<link rel="stylesheet" href="{% static 'website/form.css' %}">
<style>
    .error {
        color: red;
    }
</style>

<h2>Please Log In</h2>
<div class="main-centered">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {% if error %}
        <span class="error">{{error}}</span>
        {% endif %}
        <input type="submit" value="Submit">
    </form>
</div>

website/templates/website/logo_and_header.html
{% load static %}
<div id="header">
    <h1>{{ header }}</h1>
    <div id="logo">
        <a href="{% url 'website:index' %}">
            <img src="{% static 'website/images/logos/TTL-logo-alt.svg' %}" alt="Trivia Time Live Logo">
        </a>
    </div>
</div>

website/templates/website/navbar.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'website/navbar.css' %}" />

<div id="navbar">
    <div class="dropdown">
        <button>About</button>
        <div class="content">
            <a href="{% url 'website:about' %}">Details</a>
            <a href="{% url 'website:how_to_play' %}">How To Play / FAQ</a>
        </div>
    </div>
    <a href="{% url 'website:venues' %}">Where To Play</a>
    <div class="dropdown">
        <button>Pennant</button>
        <div class="content">
            <a href="{% url 'website:pennant_about' %}">What <i>is</i> the pennant?</a>
            <a href="{% url 'website:pennant_standings' %}">Standings</a>
        </div>
    </div>
    <div class="dropdown">
        <button>TriviaPalooza</button>
        <div class="content">
            <a href="{% url 'palooza:about' %}">What <i>is</i> TriviaPalooza?</a>
            <a href="{% url 'palooza:discounts' %}">Venue Discounts</a>
            <a href="{% url 'palooza:standings' %}">Standings</a>
        </div>
    </div>
    <a href="{% url 'website:contact_questions' %}">Contact</a>
    <!--<div class="dropdown">-->
      <!--<button>Contact</button>-->
      <!--<div class="content">-->
        <!--<a href="{% url 'website:hire_us' %}">Hire Us</a>-->
        <!--<a href="{% url 'website:apply' %}">Host For Us</a>-->
        <!--<a href="{% url 'website:contact_questions' %}">Questions</a>-->
      <!--</div>-->
    <!--</div>-->
</div>

<script type="text/javascript">
    function dropdownClick() {
        // Toggle the visibility of the dropdown content in the navbar
        var button  = this,
            content = button.nextElementSibling,
            dropdowns = Array.prototype.filter.call(
                document.querySelectorAll('.content.active'),
                function(d) { return d !== content; });
        forEach(dropdowns, function(d) { d.classList.remove('active'); })
        toggleClass(content, 'active');
    };

    // navbar: display dropdown menus when clicked
    var dropdowns = document.querySelectorAll('.dropdown>button');
    forEach(dropdowns,
        function(button) { button.onclick = dropdownClick; });

    // close dropdown if user clicks outside of it
    window.onclick = function(e) {
        if(!e.target.matches('.dropdown>button')) {
            var dropdowns = document.querySelectorAll('.content.active');
            forEach(dropdowns, function(d) { d.classList.remove('active'); })
        }
    }
</script>

website/templates/website/updates_navbar.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'website/navbar.css' %}" />
<div id="navbar">
    <!--I don't have any links that require dropdowns yet, but this is how to do it-->
    <!--<div class="dropdown">-->
        <!--<button>About</button>-->
        <!--<div class="content">-->
            <!--<a href="">Details</a>-->
            <!--<a href="">How To Play / FAQ</a>-->
        <!--</div>-->
    <!--</div>-->
    <a href="{% url 'website:move_pennant' %}">Move Pennant</a>
    <a href="{% url 'website:update_standings' %}">Update Pennant Standings</a>
    <a href="{% url 'palooza:checkins_add' %}">TriviaPalooza Checkins</a>
    <a href="{% url 'website:fbpost' 'today' %}">Today's FB post</a>
    <a href="{% url 'website:fbpost' 'tomorrow' %}">Tomorrow's FB post</a>
    <a href="{% url 'website:logout' %}">Logout</a>
</div>